language: node_js # 编译语言、环境
node_js: stable #Node.js 版本

# Travis-CI Caching
cache:
  directories:
    - node_modules

branches:
  only:
    - master # 只有master分支更改才触发CI

before_install: 
  - npm install gitbook-cli # 安装 gitbook

install:
  - npm install # 安装依赖

script: # 执行脚本，生成静态文件
  - gitbook build

deploy:
  provider: pages
  skip_cleanup: true # 跳过清理
  local_dir: _book # 需要推送到Github的静态文件目录 
  name: $GIT_NAME # 用户名变量
  email: $GIT_EMAIL # 用户邮箱变量
  github_token: $GITHUB_TOKEN # GitHub Token变量
  keep-history: true # 保持推送记录，以增量提交的方式
  target-branch: gh-pages # 推送的目标分支 local_dir->>gh-pages分支
  on:
    branch: master # 工作分支